export const recruitStudyData = [
  {
    recruit_post_id: 1,
    recruit_post_title: "sample1",
    recruit_post_content: "sample data 1",
    recruit_post_Team: "Sample",
    recruit_post_university: "순천향",
    recruit_post_branch: "프로그래밍",
    recruit_post_details: "프론트엔드",
    recruit_post_startDate: 1656063017127,
    recruit_post_endDate: 1656063105788,
    recruit_post_mini_img: process.env.PUBLIC_URL + `/imgData/Slider1.jpg`,
  },
  {
    recruit_post_id: 2,
    recruit_post_title: "sample2",
    recruit_post_content: "sample data 2",
    recruit_post_Team: "Sample",
    recruit_post_university: "선문",
    recruit_post_branch: "프로그래밍",
    recruit_post_details: "백엔드",
    recruit_post_startDate: 1656063017127,
    recruit_post_endDate: 1656063105788,
    recruit_post_mini_img: process.env.PUBLIC_URL + `/imgData/Slider1.jpg`,
  },
  {
    recruit_post_id: 3,
    recruit_post_title: "sample3",
    recruit_post_content: "sample data 3",
    recruit_post_Team: "Sample",
    recruit_post_university: "호서",
    recruit_post_branch: "언어",
    recruit_post_details: "토익",
    recruit_post_startDate: 1656063017127,
    recruit_post_endDate: 1656063105788,
    recruit_post_mini_img: process.env.PUBLIC_URL + `/imgData/Slider1.jpg`,
  },
  {
    recruit_post_id: 4,
    recruit_post_title: "sample4",
    recruit_post_content: "sample data 4",
    recruit_post_Team: "Sample",
    recruit_post_university: "순천향",
    recruit_post_branch: "언어",
    recruit_post_details: "토익",
    recruit_post_startDate: 1656063017127,
    recruit_post_endDate: 1656063105788,
    recruit_post_mini_img: process.env.PUBLIC_URL + `/imgData/Slider1.jpg`,
  },
  {
    recruit_post_id: 5,
    recruit_post_title: "sample5",
    recruit_post_content: "sample data 5",
    recruit_post_Team: "Sample",
    recruit_post_university: "순천향",
    recruit_post_branch: "프로그래밍",
    recruit_post_details: "프론트엔드",
    recruit_post_startDate: 1656063017127,
    recruit_post_endDate: 1656063105788,
    recruit_post_mini_img: process.env.PUBLIC_URL + `/imgData/Slider1.jpg`,
  },
  {
    recruit_post_id: 6,
    recruit_post_title: "sample6",
    recruit_post_content: "sample data 6",
    recruit_post_Team: "Sample",
    recruit_post_university: "호서",
    recruit_post_branch: "프로그래밍",
    recruit_post_details: "백엔드",
    recruit_post_startDate: 1656063017127,
    recruit_post_endDate: 1656063105788,
    recruit_post_mini_img: process.env.PUBLIC_URL + `/imgData/Slider1.jpg`,
  },
  {
    recruit_post_id: 7,
    recruit_post_title: "sample7",
    recruit_post_content: "sample data 7",
    recruit_post_Team: "Sample",
    recruit_post_university: "선문",
    recruit_post_branch: "프로그래밍",
    recruit_post_details: "프론트엔드",
    recruit_post_startDate: 1656063017127,
    recruit_post_endDate: 1656063105788,
    recruit_post_mini_img: process.env.PUBLIC_URL + `/imgData/Slider1.jpg`,
  },
  {
    recruit_post_id: 8,
    recruit_post_title: "sample8",
    recruit_post_content: "sample data 8",
    recruit_post_Team: "Sample",
    recruit_post_university: "선문",
    recruit_post_branch: "프로그래밍",
    recruit_post_details: "백엔드",
    recruit_post_startDate: 1656063017127,
    recruit_post_endDate: 1656063105788,
    recruit_post_mini_img: process.env.PUBLIC_URL + `/imgData/Slider1.jpg`,
  },
  {
    recruit_post_id: 9,
    recruit_post_title: "sample9",
    recruit_post_content: "sample data 9",
    recruit_post_Team: "Sample",
    recruit_post_university: "순천향",
    recruit_post_branch: "프로그래밍",
    recruit_post_details: "프론트엔드",
    recruit_post_startDate: 1656063017127,
    recruit_post_endDate: 1656063105788,
    recruit_post_mini_img: process.env.PUBLIC_URL + `/imgData/Slider1.jpg`,
  },
  {
    recruit_post_id: 10,
    recruit_post_title: "sample10",
    recruit_post_content: "sample data 10",
    recruit_post_Team: "Sample",
    recruit_post_university: "순천향",
    recruit_post_branch: "프로그래밍",
    recruit_post_details: "프론트엔드",
    recruit_post_startDate: 1656063017127,
    recruit_post_endDate: 1656063105788,
    recruit_post_mini_img: process.env.PUBLIC_URL + `/imgData/Slider1.jpg`,
  },
 
];
